# Generated by Django 5.2.17 on 2026-09-28 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0032_category_exclude_from_menu_category_long_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary shown in listings and used as a default meta description.",
                        verbose_name="excerpt",
                    ),
                ),
                ("body", models.TextField(verbose_name="body")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, upload_to="blog/posts/%Y/%m/%d", verbose_name="featured image"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="A post only appears on the storefront once this date has passed and status is Published.",
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="meta title"),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=255, verbose_name="meta description"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="date created"),
                ),
                ("date_updated", models.DateTimeField(auto_now=True, verbose_name="date updated")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blog_posts",
                        to="catalogue.product",
                        verbose_name="related products",
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "ordering": ("-published_at", "-date_created"),
            },
        ),
    ]
